wandb_version: 1

att_drop_rate:
  value: 0.1
dataset:
  value: dataset1
fold:
  value: 0
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 128
hid1:
  value: 256
hid2:
  value: 512
lr:
  value: 0.01
n_head:
  value: 1
weight_decay:
  value: 2.7454092680334965e-06
