wandb_version: 1

att_drop_rate:
  value: 0.4
dataset:
  value: dataset1
fold:
  value: 0
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 256
hid1:
  value: 256
hid2:
  value: 64
lr:
  value: 0.0001
mlp_layer2:
  value: 512
mlp_layer3:
  value: 256
n_head:
  value: 1
weight_decay:
  value: 9.08006213005282e-07
