wandb_version: 1

att_drop_rate:
  value: 0.4
dataset:
  value: dataset1
fold:
  value: 4
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 128
hid1:
  value: 256
hid2:
  value: 256
lr:
  value: 1.0e-05
mlp_layer2:
  value: 512
mlp_layer3:
  value: 512
n_head:
  value: 1
weight_decay:
  value: 7.308556031609997e-06
