wandb_version: 1

att_drop_rate:
  value: 0.4
dataset:
  value: dataset1
fold:
  value: 3
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 256
hid1:
  value: 512
hid2:
  value: 512
lr:
  value: 0.0001
mlp_layer2:
  value: 512
mlp_layer3:
  value: 16
n_head:
  value: 1
weight_decay:
  value: 6.5229653155421855e-06
