wandb_version: 1

att_drop_rate:
  value: 0.1
dataset:
  value: dataset1
fold:
  value: 4
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 128
hid1:
  value: 512
hid2:
  value: 16
lr:
  value: 0.001
mlp_layer2:
  value: 16
mlp_layer3:
  value: 256
n_head:
  value: 1
weight_decay:
  value: 7.62621884608304e-06
