wandb_version: 1

att_drop_rate:
  value: 0.4
dataset:
  value: dataset1
fold:
  value: 0
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 128
hid1:
  value: 64
hid2:
  value: 512
lr:
  value: 0.001
n_head:
  value: 1
weight_decay:
  value: 4.062075949513274e-06
