wandb_version: 1

att_drop_rate:
  value: 0.1
dataset:
  value: dataset1
fold:
  value: 1
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 256
hid1:
  value: 128
hid2:
  value: 512
lr:
  value: 0.001
mlp_layer2:
  value: 1
mlp_layer3:
  value: 1
n_head:
  value: 1
weight_decay:
  value: 6.71594004153581e-06
