wandb_version: 1

att_drop_rate:
  value: 0.1
dataset:
  value: dataset1
decay:
  value: 5.1640446929407156e-06
fold:
  value: 4
gan_in_channels:
  value: 1147
gan_out_channels:
  value: 8
hid:
  value: 256
hid1:
  value: 512
hid2:
  value: 128
lr:
  value: 0.01
mlp_layer2:
  value: 256
mlp_layer3:
  value: 1
n_heads:
  value: 1
